language: clojure
lein: lein2
script: lein2 sub install; LEIN_CMD=lein2 lein2 sub test :travis
branches:
  only:
    - master
jdk:
  - openjdk7
  - oraclejdk7
notifications:
  email:
    - pedestal@thinkrelevance.com
