name: Publish pedestal.io
on:
  push:
    branches:
      - master
      - 0.6-maint

jobs:
  notify-pedestal-io:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: pedestal/pedestal-docs
          token: ${{ secrets.PUBLISH_PEDESTAL_IO_PAT }}
          event-type: pedestal_master_commit
